# controllers:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute
news_list:
    path: /news
    methods: GET
    controller: App\Controller\NewsController::list

delete_news:
    path: /news/delete/{id}
    methods: POST
    controller: App\Controller\NewsController::delete